[package]
name = "rusty_markdown"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rusty_markdown"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pulldown-cmark = "0.9.2"
rustler = "0.27.0"
